### PR TITLE
fix: allow setting optional scalars to their default values

### LINKED ISSUE #23: Overwrite cannot set optional bool to false
## Description

`Overwrite` cannot set an `optional bool` field to `false`. Instead of copying the value, it clears the field to `nil`.

## Root Cause

The overwrite logic checks if the value equals the type's default:

```go
if isValid(srcFD, srcVal) && !srcVal.Equal(srcFD.Default()) {
    destRft.Set(...)  // Copy
} else {
    destRft.Clear(...)  // Clear
}
```

Since `false` is the default for bool, the condition fails and `Clear()` is called. For optional fields, `Clear()` sets the Go pointer to `nil`, not `false`.

## Reproduction

```go
dst := &MyMessage{MyFlag: proto.Bool(true)}   // *bool = &true
src := &MyMessage{MyFlag: proto.Bool(false)}  // *bool = &false

fmutils.Overwrite(src, dst, []string{"my_flag"})

// Expected: dst.MyFlag = &false
// Actual:   dst.MyFlag = nil
```

## Why This Matters

For `optional bool`, there are three states:
- `nil` - not set
- `&false` - explicitly false
- `&true` - explicitly true

The current logic makes it impossible to set a field from `&true` to `&false`.

## Suggested Fix

Check presence instead of comparing to default:

```go
if srcRft.Has(srcFD) {
    destRft.Set(srcFD, srcVal)
} else {
    destRft.Clear(srcFD)
}
```

## Environment

- fmutils version: v0.3.3
- Go: 1.21+

### PR DESCRIPTION
**Pull request by codeaucafe**
## Summary

This PR fixes a bug where `Overwrite` could not set optional scalar fields to their default values (e.g., `optional bool` to `false`, `optional int32` to `0`, `optional string` to `""`).

Fixes #23

## Problem

The existing logic in `overwrite()` compared field values to the type's default:

```go
if isValid(srcFD, srcVal) && !srcVal.Equal(srcFD.Default()) {
    destRft.Set(srcFD, srcVal)
} else {
    destRft.Clear(srcFD)
}
```

For optional fields, this caused incorrect behavior:

1. Source field is explicitly set to `false` (the default for bool)
2. `srcVal.Equal(srcFD.Default())` returns `true`
3. Code calls `destRft.Clear()` instead of `destRft.Set()`
4. For optional fields, `Clear()` sets the field to `nil` (unset), not `false`
5. Result: Cannot set an optional bool from `true` to `false`

## Solution

For fields with presence semantics (optional, oneof, message), check if the field **is set** using `Has()` rather than comparing the value to the default:

```go
if srcFD.HasPresence() {
    // For fields with presence (optional, oneof, message),
    // check if the field is set rather than comparing to default.
    // This allows setting optional scalars to their default values
    // (e.g., optional bool to false, optional int to 0).
    if srcRft.Has(srcFD) {
        destRft.Set(srcFD, srcVal)
    } else {
        destRft.Clear(srcFD)
    }
} else {
    // For fields without presence, use existing behavior
    if isValid(srcFD, srcVal) && !srcVal.Equal(srcFD.Default()) {
        destRft.Set(srcFD, srcVal)
    } else {
        destRft.Clear(srcFD)
    }
}
```

### Why This Works

For optional fields, there are three distinct states:

| Go Value | Meaning | `Has()` returns |
|----------|---------|-----------------|
| `nil` | Field is not set | `false` |
| `&false` | Field is explicitly set to false | `true` |
| `&true` | Field is explicitly set to true | `true` |

By using `Has()` instead of comparing values, we correctly distinguish between "field is unset" and "field is explicitly set to its default value".

### Fix Scope

`HasPresence()` returns `true` for:
- **Optional fields** (`optional bool`, `optional int32`, etc.)
- **Oneof fields** (fields inside a `oneof` block)
- **Message fields** (any field of message type)

The fix applies to all three, though the issue was most visible for optional scalars (`optional bool` for my team specifically). Message fields already worked correctly due to the `isValid()` check, but this change makes the logic more consistent across all field types with presence.

### CODE REVIEW

File: fmutils.go [hunk 1]
```diff
@@ -201,10 +201,23 @@ func (mask NestedMask) overwrite(srcRft, destRft protoreflect.Message) {
...
+					destRft.Clear(srcFD)
+				}
 			} else {
-				destRft.Clear(srcFD)
+				// For fields without presence, use existing behavior
+				if isValid(srcFD, srcVal) && !srcVal.Equal(srcFD.Default()) {
+					destRft.Set(srcFD, srcVal)
+				} else {
+					destRft.Clear(srcFD)
+				}
```
Comment (mennanov) [inline fmutils.go]: Looks like this entire piece of code can be replaced with just:

```go
			if srcRft.Has(srcFD) {
				destRft.Set(srcFD, srcVal)
			} else {
				destRft.Clear(srcFD)
			}
```

Could you please confirm that as well? If this is true then it makes sense to go forward with this solution.

**Review by mennanov — CHANGES_REQUESTED** [review]

File: fmutils.go (hunk 1 above)
Comment (codeaucafe) [reply fmutils.go]: yea I believe you are right actually. Sorry I missed that; don't have as much experience with the `protoreflect` API so didn't fully understand and did too much haha.

I just pushed up the commit with the refactored code.

thank you!

**Review by mennanov — APPROVED** [review]

**Comment by mennanov** [comment]
Thanks for contributing!

**Comment by codeaucafe** [comment]
No problem. Its the least I can do. Thanks for the awesome library. My team finds it very useful for our Go gRPC services.
